### ISSUE TITLE
Perhaps you meant ... giving suggestions that don't work

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/cmdstan#1118]
#### Summary:

See title.

#### Description:

See reproducible steps.

#### Reproducible Steps:

See current output.

#### Current Output:

```
~/temp2$ ./simple method=optimize tol_grad=1e-20
tol_grad=1e-20 is either mistyped or misplaced.
Perhaps you meant one of the following valid configurations?
  method=optimize optimize algorithm=bfgs bfgs tol_grad=<double>
  method=optimize optimize algorithm=lbfgs lbfgs tol_grad=<double>
Failed to parse command arguments, cannot run model.
```

The problem is that the suggested configurations don't work.

```
~/temp2$ ./simple method=optimize optimize algorithm=bfgs bfgs tol_grad=1e-20
optimize is either mistyped or misplaced.
Perhaps you meant one of the following valid configurations?
  method=optimize optimize
Failed to parse command arguments, cannot run model.
```

#### Expected Output:

A suggestion that would actually work as a cmdstan configuration.

#### Additional Information:

Nope.

#### Current Version:
v2.30.1

**Comment by jpmvferreira** [comment]
I would like to say that I am experiencing the same issue, and I am unable to configure the program properly.
I'm trying to run a model with a specific init file, changing the value of max_depth and saving the warmup (to change max_depth I am required to add both algorithm=hmc and engine=nuts for some reason).

Calling the binary therefore looks as follows (with valid environmental variables set):
```bash
$MODEL_BIN                       \
	sample                           \
	algorithm=hmc                    \
	engine=nuts                      \
	max_depth=20                     \
	num_samples=7500                 \
	num_warmup=5000                  \
	init=config/init.json            \
	data file=$DATA                  \
	output file=$OUTPUT/chain/$i.csv \
	save_warmup=1                    
```
Which always returns an error
```
save_warmup=1 is either mistyped or misplaced.
Perhaps you meant one of the following valid configurations?
  method=sample sample save_warmup=<boolean>
Failed to parse command arguments, cannot run model.
```

The only way for me to get it running is to remove max_depth=20, num_samples=7500, num_warmup=5000 and save_warmup=1!

What should I do? I need all of those options to get this thing to run properly, but I am unable to set them...
Should I open a new issue? Because this seems to go beyond just providing suggestions that don't work to not working when the correct options are provided (at least I'm very confident I am not doing anything wrong).

**Comment by WardBrian** [comment]
Arguments are order dependent, so things specific to the sampling algorithm need to be specified before things like the output file

**Comment by jpmvferreira** [comment]
You are correct, but it surprises me that it worked before then.
For future reference here's a working version of the previous code block:
```bash
$MODEL_BIN                       \
	sample                           \
	algorithm=hmc                    \
	engine=nuts                      \
	max_depth=25                     \
	num_samples=7500                 \
	num_warmup=5000                  \
	save_warmup=1                    \
	init=$FILE                       \
	data file=$DATA                  \
	output file=$OUTPUT/chain/$i.csv \
```

Apologies for hijacking the thread!
