### ISSUE TITLE
`generate_quantities` uses same seed across chains

### ISSUE THREAD

**Issue by mike-lawrence** [stan-dev/cmdstan#1146]
#### Summary:
When passing multi-chain `fitted_params` to `generate_quantities`, the same random seed is used for all chains.

#### Description:
I'm not sure this is intended behaviour or not, but I've taken to generating some parameter-agnostic random quantities in the GQ block (helpful for checking an SBC workflow), and I was surprised to discover that all my chains returned the same values for those quantities on a given iteration. There's variability across iterations, so I'm guessing the random seed is simply set to the same value for all chains. Is there an important reason this is the case, or just an oversight?

#### Reproducible Steps:
Here's an example model with a parameter-agnostic rng GQ, using cmdstanr:
```r
library(tidyverse)
library(cmdstanr)
library(posterior)

code = '
data{
    int<lower=1> n_y ;
    vector[n_y] y ;
}
parameters{
    real mu ;
}
model{
    mu ~ std_normal() ;
    y ~ normal(mu,1) ;
}
generated quantities{
    real sbc_uniform = uniform_rng(0,1) ; // parameter-agnostic GQ
    vector[n_y] y_rep ;
    for( i_y in 1:n_y ){
        y_rep[i_y] = normal_rng(mu,1) ;
    }
}
'

(
    code
    %>% cmdstanr::write_stan_file()
    %>% cmdstanr::cmdstan_model()
) ->
    mod

mod$generate_quantities(
    data = list(n_y=1,y=0)
    , fitted_params = posterior::as_draws_array(
        tibble(
            .chain = c(1,1,2,2)
            , .iteration = c(1,2,1,2)
            , .draw = 1:4
            , mu = rnorm(4)
        )
    )
    , seed = 1 # NOTE: leaving this here or commenting it off does **not** change the observed behavior
) ->
    from_gq

print(from_gq$draws())

````
#### Current Output:
```
# A draws_array: 2 iterations, 2 chains, and 2 variables
, , variable = sbc_uniform

         chain
iteration     1     2
        1 0.082 0.082      <<<--- Notice the identical values
        2 0.115 0.115      <<<--- Notice the identical values

, , variable = y_rep[1]

         chain
iteration     1     2
        1 -1.39 -0.44      <<<--- parameter-sensitive rngs are of course fine
        2 -0.49 -2.38

```

#### Expected Output:
Across-chain variability in parameter-agnostic rng GQs.

#### Additional Information:
Note that the docs in cmdstanr on `generate_quantities()` does seem to imply that each chain will get it's own random seed:

> seed
> (positive integer(s)) A seed for the (P)RNG to pass to CmdStan. In the case of multi-chain sampling **_the single seed will automatically be augmented by the the run (chain) ID so that each chain uses a different seed._** The exception is the transformed data block, which defaults to using same seed for all chains so that the same data is generated for all chains if RNG functions are used. The only time seed should be specified as a vector (one element per chain) is if RNG functions are used in transformed data and the goal is to generate different data for each chain.
> 

#### Current Version:
v2.31.0

**Comment by rok-cesnovar** [comment]
That doc is the same for the `seed` argument across all methods. We should specify that if the generated quantities do not use any parameters, all of them will produce the same results.

This is intended behaviour and I personally think is the correct behaviour. The problem here stems from how the generated quantities are used. The way you are using it is the same as if you would have run `real sbc_uniform = uniform_rng(0,1);` in transformed data and just outputting in GQ. And that should produce the same result across all chains because otherwise that is not actually running multiple chains, that is running multiple models. Which I believe is actually what SBC needs? (not super familiar with SBC, so maybe I am wrong here).

What you should do is just specify separate seeds for each "chain", even though this is technically not a chain, because its not running MCMC chains or using results from previous MCMC chains. The same would happen if you ran fixed_param with multiple chains (which is obviously not something anyone should be running), all the chains would produce the exact same results.

So if you are using multiple chains with cmdstan in the shell, just specify the seed for all of them
```r
> for i in {1..4}
    do
      ./bernoulli sample data file=bernoulli.data.json \
      output file=output_${i}.csv seed=XYZ id=${i}&
    done
```
in cmdstanr you can specify the seed as a vector, which would do the same: 
```
fit_gq <- mod$generate_quantities(fit, seed = c(123, 124, 126, 922))
```

**Comment by mike-lawrence** [comment]
> in cmdstanr you can specify the seed as a vector, which would do the same
Oh! I somehow missed that seed could be a vector, but I see now that the docs do indeed speak to that use case (I think I was distracted by the warning not to try to generate different data across chains, which is not what I was doing). I was instead resorting to looping over chains and doing multiple calls to generate_quantities, which had an uncomfortable amount of overhead.
