### ISSUE TITLE
Interface, algorithm, and engine for variational inference

### ISSUE THREAD

**Issue by dustinvtran** [stan-dev/cmdstan#149]
>  The "Samples were drawn using meanfield with ." thing is messed up in CmdStan.

From [stan-dev](https://groups.google.com/forum/#!topic/stan-dev/IB9BIGS1F_8).

The issue is `using A with B` in the print script, where `A` comes from `stan_csv.metadata.algorithm` and `B` comes from `stan_csv.metadata.engine`. We don't have both an algorithm and an engine metadata for variational inference, since we currently do `./model variational data file=data.R` so variational is already implicit and the algorithm is by default `meanfield`.

There's two possible solutions I see:
* Keep this requirement of `algorithm` and `engine` for all algorithms: abstract higher up so approximate inference in general falls under the same command: do something like `./model approximate data file=data.R`, where the algorithm is by default `variational` and the engine is by default `meanfield`. Other algorithms could then be `ep` or `inla` or something.
* Remove it, and have the print script be different for each main Stan task, e.g., `sample`, `optimize`, `variational`.

**Comment by bob-carpenter** [comment]
> On Aug 15, 2015, at 9:27 PM, Dustin Tran <notifications@github.com> wrote:
> 
> The "Samples were drawn using meanfield with ." thing is messed up in CmdStan.
> From stan-dev.
> 
> The issue is using A with B in the print script, where A comes from stan_csv.metadata.algorithm and B comes from stan_csv.metadata.engine. We don't have both an algorithm and an engine metadata for variational inference, since we currently do ./model variational data file=data.R so variational is already implicit and the algorithm is by default meanfield.
> 
> There's two possible solutions I see:
> 
> 	• Keep this requirement of algorithm and engine for all algorithms: abstract higher up so approximate inference in general falls under the same command: do something like ./model approximate data file=data.R, where the algorithm is by default variational and the engine is by default meanfield. Other algorithms could then be ep or inla or something.

I think our commands need to be more flexible and not force every
command into the same framework.

I'll understand if that's the expedient thing to do.

> 	• Remove it, and have the print script be different for each main Stan task, e.g., sample, optimize, variational.

I'm not sure what you mean by "print script."   You mean
the C++ bin/print program in CmdStan?

**Comment by dustinvtran** [comment]
Yeah, the `bin/print` command. There’s a lot of default text in there, e.g., about R-hat, which is nonsense for printing output obtained from running `optimize` too.

**Comment by bob-carpenter** [comment]
I didn't even know you could run bin/print it on optimize output.  
We can write separate commands, or have a single command with
a big switch at the top.  I think that'll be easier to maintain than
trying to shoehorn everything into the same format.  I am, of course,
in favor of reusing lower level routines when possible.

One problem we'll have if the output looks the same is that our users
will get confused and think VB is giving them traditional MCMC
output for the posterior, which it's not due to its approximate
nature (you can see the simple example of Ben's underestimating variance
in a simple unit normal).

- Bob

**Comment by betanalpha** [comment]
bin/print was written for MCMC output and nothing more.
VB should have its own output analysis parser completely
independent of the MCMC bin/print.  In particular, no claim
of accuracy should be made as there is no general procedure
for constructing such accuracy claims.

**Comment by syclik** [comment]
Well... `bin/print` was written before there was anything else.

There's no inherent reason it needs to only take MCMC output. We just need
to rewrite it.

(btw, it took me a weekend to write the first version, so if anyone wants
to rewrite the whole thing from scratch, please do. I'm not tied to the
implementation... especially since I did it before knowing how to use
Eigen... I did some silly things in that implementation.)

**Comment by syclik** [comment]
I'm closing this issue since it's just a discussion. We can open up a new issue once we have a plan of action.
