### ISSUE TITLE
Harmonize argument name: "num_thin"

### ISSUE THREAD

**Issue by ariddell** [stan-dev/cmdstan#561]
Argument name is ``num_thin`` in stan::services::sample functions but ``thin`` in CmdStan.

Settling on one would be useful, especially so since someday argument defaults and validation from CmdStan will be available for other interfaces to use.

CmdStan and stan::services use ``num_sample`` and ``num_warmup``. ``num_thin`` sounds good to me since it's obvious that a number is wanted and not a true/false value. 

Edit: typo

**Comment by bob-carpenter** [comment]
I agree we should standardize for Stan 3.

I do prefer it without the `num_` because once you start with that type marking it's not clear where to stop.  If it were boolean, would that be `bool_thin` and a string would be `str_thin`?

But that's not a strong preference.  I do strongly prefer either `num_thin` or `thin` over `n_thin`.

**Comment by rok-cesnovar** [comment]
Closing the issue as this will be addressed in the interface roadmap. Any changes to the arguments will be handled in separate issues after the roadmap is approved.
