### ISSUE TITLE
OpenCL-GPU-Routines

### ISSUE THREAD

**Issue by marivascruz** [stan-dev/cmdstan#740]
#### Summary:
Please provide a short couple sentence summary.
Hi - 
I'm trying to use GPU routines described in https://github.com/stan-dev/math/wiki/OpenCL-GPU-Routines . However, that documentation specificies that
`Currently gp3_example branch of CmdStan has integrated OpenCL support.` 
I was wondering if this has been updated in main stan-dev cmdstan? 

#### Current Version:
v2.20.0

**Comment by rok-cesnovar** [comment]
Hi @marivascruz, 

that wiki needs a huge refresher, sorry about that. Things have changed substantially since then and are still changing on a daily basis. 

The `gp3_example` was basically a branch to showcase our proposal we made a year ago for StanCon Helsinki. The things we promised are all on the develop branch of cmdstan/stan math + some more. Some are part of the 2.20 release, others will be a part of the next release (18th October).

In terms of user-facing Stan functions that have GPU support on develop we have the following: 
- cholesky_decompose and its gradient
- gp_exp_quad_cov
- mdivide_left_tri
- mdivide_right_tri
- multiply

We also have GPU support for all available GLMs:
- normal_id_glm_lpdf
- bernoulli_logit_glm_lpmf
- poisson_log_glm_lpmf
- neg_binomial_2_log_glm_lpmf
- categorical_logit_glm_lpmf
- ordered_logistic_glm_lpmf

However, the GLMs still need Stan compiler support which is hopefully also coming in two weeks. 

The most up-to-date doc currently would be our arxiv paper https://arxiv.org/abs/1907.01063 on the GPU support for Stan. But even that needs a refresher.

The most

**Comment by rok-cesnovar** [comment]
If you have any specific use cases where you would need GPU support, we are always accepting requests. GPs and GLMs were our primary use-cases for the initial GPU support releases, but we are now looking for others.

**Comment by rok-cesnovar** [comment]
Closing the stale issue. If you have any other questions please reopen.
