### ISSUE TITLE
Currently no way to specify 0x0 arguments in JSON format

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/cmdstan#775]
#### Summary:

```
data {
  matrix[0, 0] input;
}
```

is a valid Stan data block, but currently there is no way to provide this input in JSON. See: https://github.com/stan-dev/cmdstanr/issues/96

#### Description:

This is a full Stan model that can be initialized with the rdump format but not JSON:

```
data {
  matrix[0, 0] x;
}

parameters {
  real a;
}

model {
  a ~ normal(0, 1);
}
```

#### Current Version:
v2.21.0

**Comment by mitzimorris** [comment]
https://github.com/stan-dev/cmdstanr/issues/96

continuing discussion from CmdStanR issue - the suggestion is to accept dim(0) when expecting dim(0,0), dim(0,0,0), etc.

there was concern about this causing things to break; this seems unwarrented, because we're just allowing JSON inputs which are the equivalent of what you can do in Rdump.

**Comment by bbbales2** [comment]
Could we also solve this by including dimensions explicitly in the JSON format, like instead of:

```
y : [1, 2, 3]
```

Do:

```
y : { val: [1, 2, 3], dim : [1] }
```

That way:
```
y : { dim : [1] }
```

Is like a valid empty structure with shape?

**Comment by bob-carpenter** [comment]
Yes, we could define our own JSON format and routines to read and write that format and to convert from built-in formats.  A small hack to solve the size zero issue seems simpler.

**Comment by mitzimorris** [comment]
small hack requires changing stan::io::var_context class in module stan - opening issue there.
