### ISSUE TITLE
Add JSON output

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/cmdstan#789]
#### Description:

We should add a JSON output option. There wont be much performance gains on the cmdstan side (I think) but the cmdstanr and cmdstanpy interface would benefit here. With RapidJSON already included we could do this fairly straightforward.

The larger problem is that most of the writer classes are in the Stan repository and RapidJSON is included in Cmdstan. The easiest solution would probably be to move RapidJSON to Stan. The other way would be to move writers to cmdstan if no other interfaces use them? Though I imagine that would not be straightforward at all.

The other question is what to do with vector or matrix parameters. Should we still output "theta.1", "theta.2",... separately or do we make it a 2D matrix of "theta" with the 1st dimension being iteration and the second the index of theta?

My proposal for the output: 

```JSON
{
  "metadata": {
    "stan_version_major": 2,
    "stan_version_minor": 21,
    "model": "bernoulli", 
    "method": "sample",
    "sample": {
      "num_samples": 1000, 
      "num_warmup": 1000,
    }
  },
  "inverse_mass_matrix_diag": [2.91534, 2.99768, 2.74546, 3.26315, 2.51984, 3.05785, 2.60865, 3.52745],
  "samples": [
    {
      "mu": [1.0,2.0,3.0,4.0,5.0,6.0]
    },
    {
      "beta": [1.0,2.0,3.0,4.0,5.0,6.0]
    }
  ],
  "time": {
    "units": "seconds",
    "warmup": 0.231476,
    "sampling": 0.001759, 
    "total": 0.233235
  }
}
```

It would be nice to add this for the upcoming January release. We could also tackle #511 easily once we tackle this.

#### Current Version:
v2.21.0

**Comment by mitzimorris** [comment]
how about starting a design doc for this?

the problem I see here is that this format would require buffering all samples in memory during sampling and warmup in order to be able to output the above format.
the CSV format is convenient in that each iteration results it a row's worth of values streamed via the model's "write_array" function.  in other words, the sampler produces a row's worth of CSV values on each iteration.
the above JSON is arranged by columns - we would need  JSON notation which outputs one iteration's worth of values.

**Comment by mitzimorris** [comment]
@rok-cesnovar - very much support working on this initiative - I'd like to generalize it to proto-bufs as well.

**Comment by bob-carpenter** [comment]
> the above JSON is arranged by columns - we would need JSON notation which outputs one iteration's worth of values.

+1.  We absolutely need to stream output by iteration if we want to be at all efficient.  Storing columns internally will also lead to a lot memory locality issues with lots of parameters.  It's better to store it all and then transpose it once using a good blocked transpose algorithm than it is to try to build up column-major data from row-level streamed input.

Also, decisions are going to have be made on encoding, since R and Python's standard JSON readers use different formats.  

> I'd like to generalize it to proto-bufs as well.

The reason we'd been thinking about protobuf is that it's more efficient than JSON.  But the protobuf docs tell you it's not meant for big data output like draws from Stan, but they do support streaming and binary formats.

**Comment by rok-cesnovar** [comment]
Ah yes, silly me, going by iteration makes much more sense.

Will make a design doc. I would prefer handling JSON first and separate as I think this has a chance of making it in the next release. Once that is approved we can move from there.

I am not completely sure what the issue is with encoding. For JSON, the default encoding is UTF-8 which is supported in litejson and rjson that are the top R packages for reading JSON input as well as with the built-in json package in python as well as ujson which I think is the fastest json parsing python package.

**Comment by bob-carpenter** [comment]
Thanks.  I think it's NaN and infinity encodings that varies between the standard R and Python libs for JSON.  I'm also not sure what happens with denormalized numbers, which we've had problems with before in practice.

**Comment by rok-cesnovar** [comment]
Ah yes, will make sure to mention those in the design doc and see what happens wrt to the built-in and most popular Python/R packages.

**Comment by mitzimorris** [comment]
see comments in this issue w/r/t NaN etc in R and Python libs:  https://github.com/stan-dev/stan/issues/2686
