### ISSUE TITLE
AutodiffStackSingleton::instance_ translation unit

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/cmdstan#834]
#### Summary:

This issue is attached to: https://github.com/stan-dev/math/issues/1750

If the AutodiffStackSingleton::instance_ doesn't get instantiated somewhere in math, it'll need instantiated at the interfaces.

#### Current Version:
v2.22

**Comment by wds15** [comment]
the interfaces need to link this thing in, yes... but the initialization is handled by the tbb observer thing. The declaration of the TBB observer thing should probably also go into its own .cpp file (within math).

**Comment by rok-cesnovar** [comment]
Is there any action needed here? It isn't clear to me from the discussion.

**Comment by bbbales2** [comment]
Well the issue was never resolved, but I don't think it's causing any problems. I don't know what happened in rstan to work around/fix this. Do you remember @wds15 / @bgoodri ?

**Comment by wds15** [comment]
From my view there was never an issue. It is correct that our AD tape must be initialized in any given thread. Since we compile into every translational unit this TBB observer:

https://github.com/stan-dev/math/blob/develop/stan/math/rev/core/init_chainablestack.hpp

Any thread which is a TBB thread will initialize the AD tape. This includes the main "default" thread. Thus with the default single-process case there is no need to initialize anything manually nor is there any need to do that whenever you stay with TBB threads. Only threaded applications which want to run stan-math's autodiff will have to manually instantiate the AD tape by keeping an instance of stan::math:: ChainableStack around.

From my perspective we are fine and we can close this.

**Comment by bbbales2** [comment]
> From my view there was never an issue.

The issue was https://github.com/stan-dev/math/issues/1750.

It got resolved somehow. I remember the problem was triggered by some weird combination of things compiled before and after the CRTP model stuff. In some situations it ended up there were two translation units and if they were compiled with the right flags the runtime didn't have a problem with the duplicate symbols and then if they were compiled with different flags then the runtime did have a problem with duplicate symbols and things crashed.

I just don't remember if the combination of things was something we hacked around and we should remember to fix that hack or if there was actually a nice solution in rstan.

# we can close this.

Well what was the fix? As I recall this was a pretty annoying thing to track down because it was a weird runtime link thing in R, and creating a separate translation unit for this object to be initialized in wasn't that hard as I recall. What's happening now is anything that includes math gets one of these, and we're depending on the linker sorting out there's two of them and what to do.
