### ISSUE TITLE
pre-compiled binaries for Mac, Windows - maybe Linux?

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstan#892]
#### Summary:
for each release, make downloadable binaries for Mac, Windows, and Linux.
this extends https://github.com/stan-dev/cmdstan/issues/870

#### Description:
this feature would be useful for CmdStanX wrappers - it would speed up initial installation.
for Mac and Windows users, we would have to decide whether or not to install anticipating
use of map_rect and threading on or off.    we also need to determine whether or not
we need separate versions for Mac OS pre-catalina / catalina  and Windows 10 vs. older.

#### Current Version:
v2.23.0

**Comment by mitzimorris** [comment]
@rok-cesnovar @serban-nicusor-toptal - is this doable in general?

**Comment by rok-cesnovar** [comment]
We could build stansummary, diagnose and the deprecated print as those are actual executables and they dont rely on any libs I think. We cant build main.o or precompiled headers, especially the latter is compiler version dependent. 

Benefits of doing this are: 
- smaller tarballs to download (only the OS-specific stanc3, a bit is added due to bin/*.exe files though)
- faster install for Mac/Win (see below for times), especially if you build with `-j2`

Drawbacks: 
- more complicated release
- additional install logic in cmdstanX dependent on the OS and cmdstan version

All in all, for me it's a "draw". If users install with 2 cores at least (which should be the default in cmdstanX probably), the gain isn't really worth it.

What we would gain install-time-wise (Ubuntu g++ example):

Current state:

`time make build -j1`
```
real    1m52,732s
user    1m47,255s
sys     0m5,708s
```

`time make build -j2`
```
real    0m58,762s
user    1m51,038s
sys     0m5,801s
```

`time make build -j4`

```
real    0m46,807s
user    2m11,850s
sys     0m6,737s
```

With diagnose, stansummary and print pre-built:

`time make build -j1`
```
real    1m16,432s
user    1m11,976s
sys     0m4,298s
```

`time make build -j2`
```
real    0m41,918s
user    1m18,746s
sys     0m4,625s
```

`time make build -j4`

```
real    0m36,349s
user    1m25,050s
sys     0m4,839s
```

**Comment by mitzimorris** [comment]
many thanks for the above - closing this issue.  we need a package installer, not this.
