### ISSUE TITLE
stansummary:  separate sections for summaries of sampler parameters and model parameters

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstan#903]
#### Summary:
Aki says: https://discourse.mc-stan.org/t/cmdstan-guide-now-online/16368/10
>  there is no sense computing or reporting Rhat or ESS for sampler diagnostic columns.

#### Description:
The first several rows reported by stansummary are of no practical use w/r/t assessing the fit;
the `diagnose` command correctly analyzes these columns.
Therefore, if possible, skip the computation altogether, if not, don't report the statistics.

#### Current Output:
Example here: https://mc-stan.org/docs/2_23/cmdstan-guide/mcmc-intro.html#summarizing-sampler-outputs-with-stansummary

Discussion in discourse starts here - item 4: https://discourse.mc-stan.org/t/cmdstan-guide-now-online/16368/7

#### Expected Output:
Include summary for `lp__` or not?

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.23.0

**Comment by betanalpha** [comment]
Please do not.  The summaries of the sampler parameters (importantly the mean, 
variance, and quantiles) are informative of the fitting behavior and ar not included 
in stansummary.  The Rhat and ESS are incidental and maintain the formatting of
the output.  The inclusion of the sampler parameters in the output was an explicit 
choice.

**Comment by mitzimorris** [comment]
thank you Michael, that's a valid point.

since we now have the `diagnose` program as well, we could include the
summary of the sampler parameters at the beginning of the output;
also provide them as .csv, without the Rhat and ESS columns.
would this make sense concept-wise and reporting-wise?

**Comment by bob-carpenter** [comment]
I appreciate the report of sampler diagnostics and prefer it to the way RStan elides them from reporting. 

As a Stan dev, I know a bunch of columns are meaningless, so just ignore them.  But it has been a source of confusion fo rusers, who often try to follow our advice like all R-hat values should be near 1 or who have no idea what these things are that are being reported.

If the sampler diagnostics could be visually separated and reported without R-hat, ESS, etc., I think it'd be less confusing at the cost of two vertical lines (one space and one additional header).

**Comment by mitzimorris** [comment]
good idea.  save option would require 2 sets of csv files - with and w/out Rhat and ESS columns.

**Comment by bob-carpenter** [comment]
I was only talking about display.  I haven't through through storage, though two different files may make separating display easier---no magic names of parameters to treat differently.

**Comment by betanalpha** [comment]
The CSV output was explicitly designed to integrate the sampler parameters and the model 
parameters to facilitate analyzing them together (plotting divergent transitions against non
divergent transitions, identifying how the trajectory lengths might be spatially varying, 
etc).  Splitting the information up like RStan and PyStan do requires error-prone and
frustrating realignment.

Moreover the algorithm I/O streams everything at once so that the output format is the
same regardless of what sampler parameters an algorithm returns.  The current CmdStan 
output and diagnostics run over all columns, sampler and model parameter alike, in the 
same way so that they will be invariant to the specific sampler parameters returned.
In this way the stansummary code has been robust to not only the addition of n_leapfrog,
divergent, and energy diagnostic parameters but also the different sampler parameters
returned for the static algorithm.

In addition to these logistical challenges `diagnose` is meant to provide explicit checks 
on certain behaviors, not a general report of the sampler behavior.  Summaries of that  
behavior have always been provided with the sampler parameter rows in stansummary,
allowing users to browse the general behavior (distribution of treedepths and leapfrog
steps, average acceptance probability, number of divergences, etc) before considering 
the model parameter summaries.

**Comment by mitzimorris** [comment]
> The current CmdStan output and diagnostics run over all columns, sampler and model parameter alike, in the same way so that they will be invariant to the specific sampler parameters returned.

understood.   the solution is to differentiate between sampler and model parameters and do the right thing by both.

**Comment by mitzimorris** [comment]
hi @betanalpha,  renamed this issue to make it clear that we're not getting rid of sampler parameter summary stats.
I've submitted a PR which cleans up both the code and the output - https://github.com/stan-dev/cmdstan/pull/907
the refactored code is more general and will make it easier to change the reporting going forward.
does this answer your concerns?

**Comment by betanalpha** [comment]
It does not.  The problem is that the comment from Aki that motivated this PR
originally is fundamentally incorrect.  All of the sampler diagnostics can be
considered functions on the phase space of sampling algorithm, in which 
case effective sample size and Rhat are well-defined.  Moreover, for the 
evaluation of a fit they can be quite informative — large Rhats indicate 
differing algorithmic behavior between the chains; low effective sample sizes
indicate large autocorrelations in algorithmic behavior that might arise, 
for example, when the sampler transitions from one region of the posterior to
another.

There is simply no reason to not print all of the summary information for all 
of the sampler parameters in addition to the model parameters.  Provided
that all of the columns are printed I don’t have any problem with a line 
separating the sampler parameter summaries and the model parameter 
summaries, or even introducing proceeding headers like “Summaries for 
sampler parameters:” and “Summaries for model parameters:”.

The PR also seems to have ended up encompassing more changes than the 
original target, and splitting it up into separate PRs might avoid any confusion.

**Comment by mitzimorris** [comment]
#907
