### ISSUE TITLE
Why is seed = 0 not allowed

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/cmdstan#941]
This is just a question, not really an issue. 

Why is seed=0 not allowed in cmdstan, but is in rstan? The check in cmdstan is seed > 0.

Any specific reason or just arbitrary?

**Comment by jgabry** [comment]
No idea, good question. Hopefully someone else remembers if there was a reason for this.

**Comment by wds15** [comment]
Don’t we use the seed and multiply it with large numbers to seed the different chains? The Stan services should have the answer...and I would check there to see how the seed is being used.

**Comment by rok-cesnovar** [comment]
Thanks for the pointer. Here it is: https://github.com/stan-dev/stan/blob/develop/src/stan/services/util/create_rng.hpp
 

inline boost::ecuyer1988 create_rng(unsigned int seed, unsigned int chain) {
  using boost::uintmax_t;
  static uintmax_t DISCARD_STRIDE = static_cast<uintmax_t>(1) << 50;
  boost::ecuyer1988 rng(seed);
  rng.discard(DISCARD_STRIDE * chain);
  return rng;
}

So seed is just used to intialize the boost rng. I dont see a reason it has to be > 0 though.

**Comment by bbbales2** [comment]
Is there any interaction with the `id` argument anywhere?

**Comment by mitzimorris** [comment]
early on in the Stan code, things were set up thinking that user might want to specify the specific random number generator - then they realized that boost::ecuyer1988 was good enough.

it's possible that zero was excluded because some RNGs might not accept seed of zero?

**Comment by mitzimorris** [comment]
> Is there any interaction with the id argument anywhere?

the seed argument is fed into the RNG constructor, then the id argument is used to advance the RNG

**Comment by rok-cesnovar** [comment]
> Is there any interaction with the `id` argument anywhere?

To clarify as it may not be clear from what I wrote before, the `id` argument from cmdstan is used for the `chain` argument in the call to the above function. And `chain` is used as Mitzi describes. 

So from what I gather there is no reason we would not modify the limit to be >= 0 instead of > 0. Given that rstan calls the same utility function without any reported problems, I think it's best if we unify the valid conditions across interfaces. Not a huge priority, but also a simple fix.

**Comment by bbbales2** [comment]
@syclik any memory of this? Otherwise it's probably easiest to just verify rstan and cmdstan are doing exactly the same thing and just switch to the rstan way.

I was looking at Boost rngs to figure out the seed thing. They say integer (implying no constraint on seed): https://www.boost.org/doc/libs/1_74_0/doc/html/boost_random/reference.html#header.boost.random.additive_combine_hpp

But down the page there's a table to choose your rng -- Is it true that our RNG is both worse and slower than mt19937 (I think I saw that in a Cuda example one so I assume it's standard lol)? It's hard for me to believe that since our rng is apparently an lcg and that is supposed to be simple? That is confusing to me but I don't know the details.

**Comment by bbbales2** [comment]
I dunno, those perf numbers in the table strike me as wrong. Cuz we can pick from the same table rngs that apparently have higher quality rngness that are both slower or faster (regardless of how the speed column works)

**Comment by syclik** [comment]
> @syclik any memory of this? Otherwise it's probably easiest to just verify rstan and cmdstan are doing exactly the same thing and just switch to the rstan way.

I can't remember a good reason. I was thinking that `0` was reserved for the default since it's an `unsigned int` as the internal storage type, but it's `-1`. (There's no `NaN` for unsigned ints; -1 probably isn't the best choice either.) But no, I don't see a good reason.

> Is it true that our RNG is both worse and slower than mt19937

There was a good reason for using ecuyer1988.

See: https://groups.google.com/g/stan-dev/c/C8xa0hiSWLY/m/WuRrVE3K5ZQJ

From that thread, @bob-carpenter wrote:

> The two we're looking at are:
> 
> Mersenne Twister:
> reasonably fast samples
> very long cycle before repeats (2**19000)
> slow skip-ahead
> 
> L'Ecuyer:
> slower samples (8% speed of Mersenne)
> shorter cycle before repeats (2**61)
> fast skip-ahead
> 
> To absolutely guarantee non-overlap of
> the sequences, you need something like L'Ecuyer.

There's more on the thread...

**Comment by bbbales2** [comment]
Oooooo, interesting. Good 8-year recall on that one!

**Comment by bob-carpenter** [comment]
No reason we can't have zero.  The underlying seed representation is an unsigned int (and I think that's only 32-bit).  But if we pass in something larger than a 32-bit integer, it'll just mod down to a smaller one, so no big deal.

It'd be easy to swap out RNGs, but efficiency isn't a concern as we make very few RNG calls compared to everything else going on in HMC.  I actually don't think skipping ahead is such a big concern.  We've never been able to break anything by using "dumb" choices of RNGs (like say using one RNG to generate a few more seeds, then just using those).
