### ISSUE TITLE
QEMU emulation of stanc3 on architectures without provided binaries

### ISSUE THREAD

**Issue by StaffanBetner** [stan-dev/cmdstan#956]
#### Description:
My suggestion is that QEMU is used for unsupported architectures (probably mainly ARM64) to run stanc3. On my Android phone I replaced the stanc3 binary with a script calling the linux-stanc3 binary through QEMU, which worked very well. An alternative would be to provide ARM64 binaries of stanc3, although I have literally no idea whether they would work on both say Android and Mac OS X.

#### Current Version:
v2.25.0

**Comment by rok-cesnovar** [comment]
Thanks. 

> whether they would work on both say Android and Mac OS X

They would not but for MacOS we are fine as long as the user has Rosetta 2 installed, which most if not all M1 macOS users will have anyways.

We probably could make Linux ARM binaries but emulation seems like an easier solution to me. Especially given that compiling form Stan to C++ is not nearly the bottleneck and emulating it is fine performance-wise.

The idea I have right now would be to have a makefile flag like STANC3_EMU that users of ARM CPUs would set. For example you would set

STANC3_EMU=qemu-x86_64

and that would mean that instead of `bin/stanc` we run `qemu-x86_64 bin/stanc`.

**Comment by rok-cesnovar** [comment]
We now offer a linux ARM tarball for cmdstan releases (they include a stanc3 binary built for Linux ARM) so we can close this: https://github.com/stan-dev/cmdstan/releases/tag/v2.26.1
